version: "3"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - "54320:5432"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # - /app/node_modules
      - ./server/src:/app/src
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=54320
      - SECRET=wr3r23fwfwefwekwself.2456342.dawqdq
    ports:
      - "4000:4000"
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      #- ./client:/app
    # ports:
    #   - '1235:1235'
